name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      HAPPO_API_KEY: ${{ secrets.HAPPO_API_KEY }}
      HAPPO_API_SECRET: ${{ secrets.HAPPO_API_SECRET }}

    strategy:
      matrix:
        storybook-version: [5, 6]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - run: yarn install --frozen-lockfile
    - run: yarn add @storybook/addons@${{ matrix.storybook-version }} @storybook/react@${{ matrix.storybook-version }} && rm -rf node_modules && yarn install && yarn build && yarn happo run
    - run: HAPPO_USE_PREBUILT_PACKAGE=yes yarn build-storybook && yarn happo run
